# Generated by Django 2.0.3 on 2019-12-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191212_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='college',
            field=models.CharField(blank=True, choices=[('其他', '其他'), ('城市经济与公共管理学院', '城市经济与公共管理学院'), ('工商管理学院', '工商管理学院'), ('经济学院', '经济学院'), ('会计学院', '会计学院'), ('劳动经济学院', '劳动经济学院'), ('文化与传播学院', '文化与传播学院'), ('管理工程学院', '管理工程学院'), ('财政税务学院', '财政税务学院'), ('法学院', '法学院'), ('金融学院', '金融学院'), ('统计学院', '统计学院'), ('外国语学院', '外国语学院'), ('华侨学院', '华侨学院'), ('马克思主义学院', '马克思主义学院'), ('国际经济管理学院', '国际经济管理学院'), ('国际学院', '国际学院'), ('继续教育学院', '继续教育学院')], default='其他', max_length=100, null=True, verbose_name='学院'),
        ),
    ]
